In [1]:
import numpy as np
import pandas as pd
import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns

In [17]:
df = pd.read_excel("./Data/demographics.xls", engine="xlrd")
df = df.rename(columns={
    'Weight (kg)' : 'weight',
    'Height (meters)' : 'height'
})
df.describe()
df.info()
df["Group"] = df["Group"].replace({"CO": "Control", "PD": "Patient"})
df["Gender"] = df["Gender"].astype(str).str.strip().str.lower()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 166 entries, 0 to 165
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ID                166 non-null    object
 1   Study             166 non-null    object
 2   Group             166 non-null    object
 3   Subjnum           166 non-null    int64
 4   Gender            166 non-null    object
 5   Age               166 non-null    int64
 6   height            163 non-null    float64
 7   weight            163 non-null    float64
 8   HoehnYahr         111 non-null    float64
 9   UPDRS             135 non-null    float64
 10  UPDRSM            135 non-null    float64
 11  TUAG              153 non-null    float64
 12  Speed_01 (m/sec)  165 non-null    float64
 13  Speed_10          20 non-null     float64
dtypes: float64(8), int64(2), object(4)
memory usage: 18.3+ KB

,ID,Study,Group,Subjnum,Gender,Age,height,weight,HoehnYahr,UPDRS,UPDRSM,TUAG,Speed_01 (m/sec),Speed_10
0,GaPt03,Ga,Patient,3,female,82,1.45,50.0,3.0,20.0,10.0,36.34,NaN,0.778
1,GaPt04,Ga,Patient,4,male,68,1.71,NaN,2.5,25.0,8.0,11.00,0.642,0.818
2,GaPt05,Ga,Patient,5,female,82,1.53,51.0,2.5,24.0,5.0,14.50,0.908,0.614
3,GaPt06,Ga,Patient,6,male,72,1.70,82.0,2.0,16.0,13.0,10.47,0.848,0.937
4,GaPt07,Ga,Patient,7,female,53,1.67,54.0,3.0,44.0,22.0,18.34,0.677,0.579

In [25]:
df['height'] = df['height'].fillna(df.groupby('Gender')['height'].transform('median'))
df['height_group'] = pd.cut(df['height'], bins=[1.4, 1.6, 1.75, 2.0])
df['weight'] = df['weight'].fillna(df.groupby(['Gender', 'height_group'])['weight'].transform('median'))
df

/var/folders/36/f5l6dqb10vd9g2s63fv1y2kr0000gn/T/ipykernel_19430/2860804890.py:3: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df['weight'] = df['weight'].fillna(df.groupby(['Gender', 'height_group'])['weight'].transform('median'))

,ID,Study,Group,Subjnum,Gender,Age,height,weight,HoehnYahr,UPDRS,UPDRSM,TUAG,Speed_01 (m/sec),Speed_10,height_group
0,GaPt03,Ga,Patient,3,female,82,1.45,50.0,3.0,20.0,10.0,36.34,NaN,0.778,"(1.4, 1.6]"
1,GaPt04,Ga,Patient,4,male,68,1.71,75.0,2.5,25.0,8.0,11.00,0.642,0.818,"(1.6, 1.75]"
2,GaPt05,Ga,Patient,5,female,82,1.53,51.0,2.5,24.0,5.0,14.50,0.908,0.614,"(1.4, 1.6]"
3,GaPt06,Ga,Patient,6,male,72,1.70,82.0,2.0,16.0,13.0,10.47,0.848,0.937,"(1.6, 1.75]"
4,GaPt07,Ga,Patient,7,female,53,1.67,54.0,3.0,44.0,22.0,18.34,0.677,0.579,"(1.6, 1.75]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
161,SiCo26,Si,Control,26,male,60,1.74,72.0,NaN,NaN,NaN,9.20,1.000,NaN,"(1.6, 1.75]"
162,SiCo27,Si,Control,27,male,67,1.90,95.0,NaN,NaN,NaN,12.52,1.120,NaN,"(1.75, 2.0]"
163,SiCo28,Si,Control,28,male,61,1.70,72.0,NaN,NaN,NaN,12.65,0.990,NaN,"(1.6, 1.75]"
164,SiCo29,Si,Control,29,male,53,1.70,87.0,NaN,NaN,NaN,11.41,1.290,NaN,"(1.6, 1.75]"
165,SiCo30,Si,Control,30,male,63,1.74,82.0,NaN,NaN,NaN,8.68,1.420,NaN,"(1.6, 1.75]"